version: '3'

services:
  geo:
    restart: on-failure
    container_name: ${APP_NAME} 
    build: .
    env_file:
      - .env
    depends_on:
      - db_geo
      - redis
      - rabbit
    networks:
      - my_network  

  db_geo:
    image: postgres    
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"  
    networks:
      - my_network

  migrator_geo:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable",
      ]      
    command: ["up"]  
    depends_on:
      - db_geo
    restart: on-failure
    networks:
      - my_network
  
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  rabbit:
    image: rabbitmq:3-management   
    container_name: rabbit
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network  
    
networks:
  my_network:
    external: true    